get:
  tags:
    - Package
  summary: Get a list of deployment options of a sub package
  responses:
    "200":
      description: Ok
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../schemas/EnumInformation.yaml'
    "403":
      description: Unauthorized
    "500":
      description: Internal failure
post:
  tags:
    - Package
  summary: Update a list of deployment options of a sub package
  requestBody:
    content:
      application/json:
        schema:
          type: array
          items:
            type: string
            description: Document ID of a deployment option
  responses:
    "200":
      description: Ok
    "400":
      description: Invalid input
    "403":
      description: Unauthorized
    "500":
      description: Internal failure
