post:
  tags:
    - Product
  summary: Rename a product
  parameters:
    $ref: '../schemas/EnumRenameParameters.yaml'
  requestBody:
    $ref: '../schemas/EnumRenameRequestBody.yaml'
  responses:
    "200":
      description: Ok
    "400":
      description: Invalid input
    "403":
      description: Unauthorized
    "404":
      description: Product not found
    "500":
      description: Internal failure
