openapi: 3.0.0
info:
  title: RANdevU
  version: 0.0.0
servers:
  - url: http://localhost:3699
paths:
  /authenticate:
    get:
      tags:
        - User
      summary: Check if the current client is logged in
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - username
                properties:
                  username:
                    type: string
                  role:
                    type: string
        "400":
          description: Not authenticated
  /deployment-options:
    get:
      tags:
        - Deployment option
      summary: Get a list of deployment options
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - Deployment option
      summary: Add a deployment option
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /deployment-options/{name}:
    post:
      tags:
        - Deployment option
      summary: Rename a deployment option
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - nameNew
              properties:
                nameNew:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
        "403":
          description: Unauthorized
        "404":
          description: Deployment option not found
        "500":
          description: Internal failure
  /join:
    post:
      tags:
        - User
      summary: Join RANdevU
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      reason:
                        type: string
        "500":
          description: Internal failure
  /login:
    post:
      tags:
        - User
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Ok
        "401":
          description: Login failed
        "500":
          description: Internal failure
  /logout:
    get:
      tags:
        - User
      summary: Logout
      responses:
        "200":
          description: Ok
  /network-elements:
    get:
      tags:
        - Network element
      summary: Get a list of network elements
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - Network element
      summary: Add a network element
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /network-elements/{name}:
    post:
      tags:
        - Network element
      summary: Rename a network element
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - nameNew
              properties:
                nameNew:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
        "403":
          description: Unauthorized
        "404":
          description: Deployment option not found
        "500":
          description: Internal failure
  /operators:
    get:
      tags:
        - Operator
      summary: Get a list of operators
      responses:
        "200":
          description: Ok
          content:
            "application/json":
              schema:
                type: array
                items:
                  type: object
                  properties:
                    operatorName:
                      type: string
                    owner:
                      type: string
                  required:
                    - operatorName
                    - owner
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - Operator
      summary: Add an operator
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              required:
                - operatorName
                - username
              properties:
                operatorName:
                  type: string
                username:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            "application/json":
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /radio-access-technologies:
    get:
      tags:
        - Radio access technology
      summary: Get a list of radio access technologies
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - Radio access technology
      summary: Add a radio access technology
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /radio-access-technologies/{name}:
    post:
      tags:
        - Radio access technology
      summary: Rename a radio access technology
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - nameNew
              properties:
                nameNew:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
        "403":
          description: Unauthorized
        "404":
          description: Deployment option not found
        "500":
          description: Internal failure
  /ran-sharing:
    get:
      tags:
        - RAN sharing
      summary: Get a list of RAN sharing options
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - RAN sharing
      summary: Add a RAN sharing option
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /ran-sharing/{name}:
    post:
      tags:
        - RAN sharing
      summary: Rename a RAN sharing option
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - nameNew
              properties:
                nameNew:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
        "403":
          description: Unauthorized
        "404":
          description: Deployment option not found
        "500":
          description: Internal failure
  /users/{username}:
    get:
      tags:
        - User
      summary: Get information of a user
      responses:
        "200":
          description: Ok
          content:
            application:json:
              schema:
                type: object
                required:
                  - _id
                  - username
                properties:
                  _id:
                    type: string
                  username:
                    type: string
                  role:
                    type: string
        "403":
          description: Unauthorized
        "404":
          description: User not found
        "500":
          description: Internal failure
