openapi: 3.0.0
info:
  title: RANdevU
  version: 0.0.0
servers:
  - url: http://localhost:3699
components:
  schemas:
    EnumInformation:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
      required:
        - _id
        - name
    UserCredential:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    UserInformation:
      type: object
      properties:
        _id:
          type: string
        username:
          type: string
        role:
          type: string
      required:
        - _id
        - username
paths:
  /authenticate:
    get:
      tags:
        - User
      summary: Check if the current client is logged in
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInformation"
        "401":
          description: Not authenticated
  /deployment-options:
    get:
      tags:
        - Deployment option
      summary: Get a list of deployment options
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EnumInformation"
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - Deployment option
      summary: Add a deployment option
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /deployment-options/{name}:
    post:
      tags:
        - Deployment option
      summary: Rename a deployment option
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - nameNew
              properties:
                nameNew:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
        "403":
          description: Unauthorized
        "404":
          description: Deployment option not found
        "500":
          description: Internal failure
  /duplex-modes:
    get:
      tags:
        - Duplex mode
      summary: Get a list of duplex modes
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EnumInformation"
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - Duplex mode
      summary: Add a duplex mode
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /duplex-modes/{name}:
    post:
      tags:
        - Duplex mode
      summary: Rename a duplex mode
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - nameNew
              properties:
                nameNew:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
        "403":
          description: Unauthorized
        "404":
          description: Duplex mode not found
        "500":
          description: Internal failure
  /join:
    post:
      tags:
        - User
      summary: Join RANdevU
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredential"
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      reason:
                        type: string
        "500":
          description: Internal failure
  /login:
    post:
      tags:
        - User
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredential"
      responses:
        "200":
          description: Ok
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/UserInformation"
        "401":
          description: Login failed
        "500":
          description: Internal failure
  /logout:
    get:
      tags:
        - User
      summary: Logout
      responses:
        "200":
          description: Ok
  /network-elements:
    get:
      tags:
        - Network element
      summary: Get a list of network elements
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EnumInformation"
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - Network element
      summary: Add a network element
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /network-elements/{name}:
    post:
      tags:
        - Network element
      summary: Rename a network element
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - nameNew
              properties:
                nameNew:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
        "403":
          description: Unauthorized
        "404":
          description: Deployment option not found
        "500":
          description: Internal failure
  /operators:
    get:
      tags:
        - Operator
      summary: Get a list of operators
      parameters:
        - name: include
          in: query
          description: Includes related information in a response
          schema:
            type: array
            items:
              type: string
              enum:
                - owner
      responses:
        "200":
          description: Ok
          content:
            "application/json":
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    name:
                      type: string
                    owner:
                      type: object
                      properties:
                        _id:
                          type: string
                        username:
                          type: string
                      required:
                        - _id
                        - username
                  required:
                    - _id
                    - name
                    - owner
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - Operator
      summary: Add an operator
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              required:
                - name
                - owner
              properties:
                name:
                  type: string
                owner:
                  type: string
                  description: A document ID of a user
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            "application/json":
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /packages:
    get:
      tags:
        - Package
      summary: Get a list of packages
      parameters:
        - name: operator
          description: A list of operator names
          in: query
          schema:
            type: array
            items:
              type: string
        - name: include
          in: query
          schema:
            type: array
            items:
              type: string
              enum:
                - main
                - operator
                - owner
      responses:
        "200":
          description: Ok
          content:
            "application/json":
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    name:
                      type: string
                    main:
                      type: object
                      properties:
                        _id:
                          type: string
                        name:
                          type: string
                      required:
                        - _id
                        - name
                    operator:
                      type: object
                      properties:
                        _id:
                          type: string
                        name:
                          type: string
                      required:
                        - _id
                        - name
                  required:
                    - _id
                    - name
        "400":
          description: Invalid input
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - Package
      summary: Add a main or sub package
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                name:
                  type: string
                sub:
                    type: object
                    description: Subpackage information
                    properties:
                      main:
                        type: string
                        description: Document ID of a main package.
                      operator:
                        type: string
                        description: Document ID of a target operator.
                      previous:
                        type: string
                        description: Document ID of a previous subpackage.
                      owner:
                        type: string
                        description: Document ID of a user.
                    required:
                      - main
                      - operator
                      - owner
              required:
                - name
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /radio-access-technologies:
    get:
      tags:
        - Radio access technology
      summary: Get a list of radio access technologies
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EnumInformation"
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - Radio access technology
      summary: Add a radio access technology
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /radio-access-technologies/{name}:
    post:
      tags:
        - Radio access technology
      summary: Rename a radio access technology
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - nameNew
              properties:
                nameNew:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
        "403":
          description: Unauthorized
        "404":
          description: Deployment option not found
        "500":
          description: Internal failure
  /ran-sharing:
    get:
      tags:
        - RAN sharing
      summary: Get a list of RAN sharing options
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EnumInformation"
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
    post:
      tags:
        - RAN sharing
      summary: Add a RAN sharing option
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "403":
          description: Unauthorized
        "500":
          description: Internal failure
  /ran-sharing/{name}:
    post:
      tags:
        - RAN sharing
      summary: Rename a RAN sharing option
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - nameNew
              properties:
                nameNew:
                  type: string
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid input
        "403":
          description: Unauthorized
        "404":
          description: Deployment option not found
        "500":
          description: Internal failure
  /users/:
    get:
      tags:
        - User
      summary: Get a list of user information
      responses:
        "200":
          description: Ok
          content:
            application:json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserInformation"
        "403":
          description: Unauthorized
        "500":
          description: Internal failure  
  /users/docId/{docId}:
    get:
      tags:
        - User
      summary: Get information of a user by document ID
      parameters:
        - name: docId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Ok
          content:
            application:json:
              schema:
                $ref: "#/components/schemas/UserInformation"
        "403":
          description: Unauthorized
        "404":
          description: User not found
        "500":
          description: Internal failure
  /users/username/{username}:
    get:
      tags:
        - User
      summary: Get information of a user by user name
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Ok
          content:
            application:json:
              schema:
                $ref: "#/components/schemas/UserInformation"
        "403":
          description: Unauthorized
        "404":
          description: User not found
        "500":
          description: Internal failure