export const COLLECTION_CHANGE = 'change';
export const COLLECTION_CUSTOMER = 'customer';
export const COLLECTION_DEPLOYMENT_OPTION = 'deploymentOption';
export const COLLECTION_DUPLEX_MODE = 'duplexMode';
export const COLLECTION_FEATURE = 'feature';
export const COLLECTION_FEATURE_VERSION = 'featureVersion';
export const COLLECTION_NETWORK_ELEMENT = 'networkElement';
export const COLLECTION_OPERATOR = 'operator';
export const COLLECTION_PACKAGE_MAIN = 'packageMain';
export const COLLECTION_PACKAGE_SUB = 'packageSub';
export const COLLECTION_PRODUCTS = 'products';
export const COLLECTION_RADIO_ACCESS_TECH = 'radioAccessTech';
export const COLLECTION_RAN_SHARING = 'ranSharing';
export const COLLECTION_REQUIREMENT = 'requirement';
export const COLLECTION_USER = 'user';

export const EDGE_COLLECTION_COMMITS = 'commits';
export const EDGE_COLLECTION_DERIVED_FROM = 'derivedFrom';
export const EDGE_COLLECTION_DESCRIBES = 'describes';
export const EDGE_COLLECTION_FORKED_FROM = 'forkedFrom';
export const EDGE_COLLECTION_IMPLEMENTS = 'implements';
export const EDGE_COLLECTION_OWNS = 'owns';
export const EDGE_COLLECTION_REGISTERS = 'registers';
export const EDGE_COLLECTION_REQUESTS = 'requests';
export const EDGE_COLLECTION_REQUIRES = 'requires';
export const EDGE_COLLECTION_TARGETS = 'targets';
export const EDGE_COLLECTION_SUCCEEDS = 'succeeds';

export const docCollectionNameList = [
  COLLECTION_CHANGE,
  COLLECTION_CUSTOMER,
  COLLECTION_DEPLOYMENT_OPTION,
  COLLECTION_DUPLEX_MODE,
  COLLECTION_FEATURE,
  COLLECTION_FEATURE_VERSION,
  COLLECTION_NETWORK_ELEMENT,
  COLLECTION_OPERATOR,
  COLLECTION_PACKAGE_MAIN,
  COLLECTION_PACKAGE_SUB,
  COLLECTION_PRODUCTS,
  COLLECTION_RADIO_ACCESS_TECH,
  COLLECTION_RAN_SHARING,
  COLLECTION_REQUIREMENT,
  COLLECTION_USER,
];

export const edgeCollectionNameList = [
  EDGE_COLLECTION_COMMITS,
  EDGE_COLLECTION_DERIVED_FROM,
  EDGE_COLLECTION_DESCRIBES,
  EDGE_COLLECTION_FORKED_FROM,
  EDGE_COLLECTION_IMPLEMENTS,
  EDGE_COLLECTION_OWNS,
  EDGE_COLLECTION_REGISTERS,
  EDGE_COLLECTION_REQUESTS,
  EDGE_COLLECTION_REQUIRES,
  EDGE_COLLECTION_SUCCEEDS,
  EDGE_COLLECTION_TARGETS,
];
