openapi: 3.0.0
info:
  title: RANdevU
  version: 0.0.0
servers:
  - url: http://localhost:3699
paths:
  # User
  /authenticate:
    $ref: './paths/authenticate.yaml'
  /join:
    $ref: './paths/join.yaml'
  /login:
    $ref: './paths/login.yaml'
  /logout:
    $ref: './paths/logout.yaml'
  /users/:
    $ref: './paths/users.yaml'
  /users/{seqVal}:
    $ref: './paths/users_seqVal.yaml'

  # Deployment option
  /deployment-options:
    $ref: './paths/deploymentOptions.yaml'
  /deployment-options/{seqVal}:
    $ref: './paths/deploymentOption.yaml'

    # Duplex mode
  /duplex-modes:
    $ref: './paths/duplexModes.yaml'
  /duplex-modes/{seqVal}:
    $ref: './paths/duplexMode.yaml'

    # Network element
  /network-elements:
    $ref: './paths/networkElements.yaml'
  /network-elements/{seqVal}:
    $ref: './paths/networkElement.yaml'

    # Operator
  /operators:
    $ref: './paths/operators.yaml'
  /operators/{seqVal}/packages:
    $ref: './paths/operators_seqVal_packages.yaml'

  # Package
  /packages:
    $ref: './paths/packages.yaml'
  /packages/main/{seqVal}:
    $ref: './paths/packages_main_seqVal.yaml'
  /packages/main/{seqVal}/sub:
    $ref: './paths/packages_main_seqVal_sub.yaml'
  /packages/sub/{seqVal}:
    $ref: './paths/packages_sub_seqVal.yaml'
  /packages/sub/{seqVal}/operator:
    $ref: './paths/packages_sub_seqVal_operator.yaml'
  /packages/sub/{seqVal}/owner:
    $ref: './paths/packages_sub_seqVal_owner.yaml'
  /packages/sub/{seqVal}/previous:
    $ref: './paths/packages_sub_seqVal_previous.yaml'
  /packages/sub/{seqVal}/follow-ups:
    $ref: './paths/packages_sub_seqVal_followUps.yaml'
  /packages/sub/{seqVal}/deployment-options:
    $ref: './paths/packages_sub_seqVal_deploymentOptions.yaml'
  /packages/sub/{seqVal}/products:
    $ref: './paths/packages_sub_seqVal_products.yaml'
  /packages/sub/{seqVal}/radio-access-technologies:
    $ref: './paths/packages_sub_seqVal_radioAccessTechnologies.yaml'
  /packages/sub/{seqVal}/ran-sharing:
    $ref: './paths/packages_sub_seqVal_ranSharing.yaml'

  # Product
  /products:
    $ref: './paths/products.yaml'
  /products/{seqVal}:
    $ref: './paths/product.yaml'

  # RAT
  /radio-access-technologies:
    $ref: './paths/radioAccessTechnologies.yaml'
  /radio-access-technologies/{seqVal}:
    $ref: './paths/radioAccessTechnology.yaml'

  # RAN sharing
  /ran-sharing:
    $ref: './paths/ranSharings.yaml'
  /ran-sharing/{seqVal}:
    $ref: './paths/ranSharing.yaml'

  # Requirement
  /requirements:
    $ref: './paths/requirements.yaml'
